### ISSUE TITLE
Question regarding creating Pages for each Portfolio

### ISSUE THREAD

**Issue by jeon11** [somratpro/somrat#15]
Hello,

Thanks for the awesome theme. I'm pretty new to hugo, and wanted to try out this theme for my personal website. 

I had a quick question on how to create additional pages. Currently in the demo's portfolio section, clicking on the portfolio image would only move on to the next image. I was wondering if there was a guide or place to learn on how I can add pages for each portfolio piece. 

Hope my question makes sense. Any pointers would also be appreciated. Thanks!

**Comment by somratpro** [comment]
hey there, i am sorry to say that i don't working on this project anymore. i leave this issue open, so someone can help you...
