### ISSUE TITLE
Little sugestion: For a better conversion performance, would it be possible to put the social button in the 'about me' section?

### ISSUE THREAD

**Issue by AlexMaldon** [somratpro/somrat#19]
Dear Somrat,

CONGRATS for this really AMAZING hugo theme !! It's really far from any other!
I would only recommend to put the social buttons in a nearer place in order to improve your (and ours XD) porfolio conversion.
I've seen yoour personal portfolio and those button works perfectly but trying your somrat hugo theme by my own... it doesn't render the social button, I only get a tiny white rectangle for each one, not even in the 'contact ' section where they were :(

Please, I would really appreciate if you could fix them in the 'about me' section. I have try several times but it is impossible for me ;_(

Thank you so much in advance !

![Social_butttons_not_rendering](https://user-images.githubusercontent.com/12098897/106356012-763e3100-62fc-11eb-8f9e-547789749e65.PNG)

**Comment by somratpro** [comment]
hey there, I am sorry to say that I don't work on this project anymore. I leave this issue open, so someone can help you...

**Comment by ccthecode** [comment]
@AlexMaldon To fix icon issue, go to layouts/partials/script.html

```diff
{{ "<!-- Main Script -->" | safeHTML }}
{{ $script := resources.Get "js/script.js" | minify}}
- <script src="{{ $script.Permalink }}"></script>
+ <script src="{{ $script.Permalink }}"></script>
```
