### ISSUE TITLE
Is it possible to link external .md pages from the main menu items and customize the main section?

### ISSUE THREAD

**Issue by gabrielelissia** [somratpro/somrat#20]
Hi Somrat! I've found your Hugo template and I like it very very much. I'm a musician and I'd like to create my own website, with my info, some media and a contact module, so exactly what your template offers. I've only some problems, and I'd like to ask you some help, if you can:

- when I'm modifying the main menu I'd like for some items to redirect to an external .md page (for example I have a chamber music project, and instead of having our bio, pics etc. in the main page I'd like to separate it from my homepage, and having an .md file would also allow me to put a photo and some youtube video links in the page). The problem is that when I'm launching the hugo command I can't find the .md pages in the public folder nor into some site path, as the template doesn't allow them to be created. I'm not a coder, only a musician with the passion for technology, so maybe I'm doing something wrong. Does your template allow this possibility, the creation and link of external pages from the main menu buttons? I’d like also maybe in the future to open also a kinda « blog section » on my site, so having the possibility to add section to my main menu and linking them to external pages would be fundamental for me;

- when dealing with the sections of your template into the main homepage I'd like to modify some of them, for example in the "portfolio" section I'd like to substitute the project pages with the music/video programs that I master, as a list of my creator’s abilities. But for some reason the icons are too big, I’d like them to be a lot smaller, but the image dimension is stuck to 400x400, and the title of the apps is also too big, so it’s not properly shown. Why is that? Can I modify all those parameters, as the title and image dimensions, or the theme doesn’t allow me this grade of customization?

If you could help me understand those two issues I’d be happy to use your beautiful template as my site.

Thank you very much,

Sincerely,

Gabriele

**Comment by somratpro** [comment]
Hello @gabrielelissia 

As you see, this theme is archived, and I am not able to help you anymore. Only I can suggest you discuss it on Hugo Forum, there are a lot of developers, I am pretty sure they can help you out.
