### ISSUE TITLE
Portfolio/Testimonials issue

### ISSUE THREAD

**Issue by jsnhubbard** [somratpro/somrat#9]
Hello,
I am completely new to github, coding (forestry/netlify which I am using in conjunction with this Hugo theme). Please bear with me. I just want to get rid of the Portfolio section altogether. When I uncheck the box for that in forestry, I lose Testimonials section on the website (but it still displays the word Testimonials). Here is the site: https://jsnhubbard.netlify.app/
I am using forestry to have a graphic interface and not having to type in any code at all so if there are suggestions to fix this issue with code, I honestly wouldn't know where to input it but I am very willing to learn!
If you need more info, let me know and thanks for any help!
Jason

**Comment by ryvaeus** [comment]
Disabling the Portfolio section seems to cause an `Uncaught TypeError: Cannot read property 'className' of undefined` error that breaks owl carousel. Not sure how to fix, hopefully @somratpro checks in.

**Comment by coffemanfp** [comment]
I have the same problem.
